### ISSUE TITLE
Error: "Cannot overwrite directory" during install

### ISSUE THREAD

**Issue by lincolnthree** [mapiacompany/capacitor-codepush#13]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

After user confirms "Install" (or non-dialog install), the following error occurs during copying of files:

```
index.js:78 native Filesystem.copy (#35089827):

Object:
{
callbackId: "82559909"
methodName: "copy"
options:
directory: "DATA"
from: "codepush/download/unzipped"
to: "codepush/deploy/versions/e07143b920ba863f8a1d1c909d584963655e6a7df9ee85f7681f0995a76f5ab3"
toDirectory: "DATA"
__proto__: Object
pluginId: "Filesystem"
__proto__: Object
}
```

```codePushUtil.js:47 [CodePush]  Cannot overwrite a directory. StackTrace: Error: Cannot overwrite a directory
    at Object.cap.fromNative (http://10.0.0.3:8100/vendor.js:88789:24)
    at <anonymous>:1:18
logError @ codePushUtil.js:47
push.Yr+L.CodePushUtil.invokeErrorCallback @ codePushUtil.js:59
installError @ localPackage.js:44
(anonymous) @ localPackage.js:70
rejected @ localPackage.js:5
invoke @ zone-evergreen.js:372
onInvoke @ core.js:28579
invoke @ zone-evergreen.js:371
run @ zone-evergreen.js:134
(anonymous) @ zone-evergreen.js:1276
invokeTask @ zone-evergreen.js:406
onInvokeTask @ core.js:28566
invokeTask @ zone-evergreen.js:405
runTask @ zone-evergreen.js:178
drainMicroTaskQueue @ zone-evergreen.js:582
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:565
scheduleTask @ zone-evergreen.js:396
onScheduleTask @ zone-evergreen.js:283
scheduleTask @ zone-evergreen.js:386
scheduleTask @ zone-evergreen.js:221
scheduleMicroTask @ zone-evergreen.js:241
scheduleResolveOrReject @ zone-evergreen.js:1266
resolvePromise @ zone-evergreen.js:1204
(anonymous) @ zone-evergreen.js:1120
cap.fromNative @ index.js:297
(anonymous) @ VM2627:1
15:22:59.417 codePushUtil.js:47 [CodePush] An error occurred during sync. Cannot overwrite a directory. StackTrace: Error: Cannot overwrite a directory
    at Object.cap.fromNative (http://10.0.0.3:8100/vendor.js:88789:24)
    at <anonymous>:1:18
```

### Reproduction

1. Ensure update is available in AppCenter
2. Run the app with this plugin installed
3. Call `codePushUtil.sync()`

### Additional Information

* cordova-plugin-code-push version: This repo
* List of installed plugins: 
```
[info] Found 20 Capacitor plugins for ios:
       @capacitor-community/http@0.3.0
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/device@0.5.3
       @capacitor/dialog@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-codepush@1.0.0
       capacitor-firebase-auth@2.3.5
       capacitor-rate-app@1.0.0
[info] Found 2 Cordova plugins for ios:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
```

* Capacitor version: 3.0.0-beta.6
* iOS/Android/Windows version: iOS 14, Android 11
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by lincolnthree** [comment]
This seems to happen after an update was downloaded, but not installed. A second download is performed, then fails on unzip.

I think the plugin is possibly not detecting an existing completed download? E.g. It should not have to download again in this case?

**Comment by leo6104** [comment]
Thank you for reporting the problem. 

Fix this problem with https://github.com/mapiacompany/capacitor-codepush/commit/bc355d9d17c4f883a45dac8f658562a8020c2c2c

**Comment by lincolnthree** [comment]
Perfect! This is a much better fix than my patch :)
