### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.codePush.reportStatus')

### ISSUE THREAD

**Issue by lincolnthree** [mapiacompany/capacitor-codepush#31]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I'm not sure why this is happening, but a small subset of devices the codePush instance seems unavailable in the window context. Possibly a timing issue? This is strange though because our app waits a solid 4-5s before attempting any CodePush actions.

```
TypeError: undefined is not an object (evaluating 'window.codePush.reportStatus')
  at ionic:(//localhost:1:71)
  at ? (ionic://localhost/polyfills-es2015.6efff9e9e083b048c166.js:1:40938)
  at runTask(ionic://localhost/polyfills-es2015.6efff9e9e083b048c166.js:1:11465)
  at invokeTask(ionic://localhost/polyfills-es2015.6efff9e9e083b048c166.js:1:17103)

```

### Reproduction

No reproduction available currently. Just production logging messages.

### Additional Information

* cordova-plugin-code-push version: latest
* List of installed plugins:
* Cordova version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical & unknown

(The more info the faster we will be able to address it!)

**Comment by lincolnthree** [comment]
Actually this seems to be quite common:

![image](https://user-images.githubusercontent.com/362329/115925756-ad316800-a44f-11eb-9abb-0165a5de66cd.png)

It only seems to be occurring on Android:

![image](https://user-images.githubusercontent.com/362329/115925808-c2a69200-a44f-11eb-85e1-6cf1292e25ba.png)

**Comment by lincolnthree** [comment]
This appears to be an issue when the CodePush TS/JS library is not loaded at the time when the native plugin attempts to register the `onDeviceReady` listener. The injected/eval JS hooks in the native CodePush manager code for Android/iOS should probably be refactored to handle this situation.

Since Capacitor does not guarantee the client JS code is loaded until the application imports the CodePush libraries (unlike Cordova which loads all plugin code up front), we will need to provide deferred callback support in the platform reporting managers:

1. https://github.com/mapiacompany/capacitor-codepush/blob/main/ios/Plugin/CodePushReportingManager.m#L36
2. https://github.com/mapiacompany/capacitor-codepush/blob/main/android/src/main/java/com/microsoft/capacitor/CodePushReportingManager.java#L32

Something like this:
```
if(window.codePush) {
   javascript:document.addEventListener(\"deviceready\", function () { window.codePush.reportStatus(%d, %s, %s, %s, %s, %s); });
} else {
   window.codePushReportStatus = function () { window.codePush.reportStatus(%d, %s, %s, %s, %s, %s); });
}

```

Then in `codePush.ts` here: https://github.com/mapiacompany/capacitor-codepush/blob/main/src/codePush.ts#L525

```
export const codePush = new CodePush();
(window as any).codePush = codePush;
if(window.codePushReportStatus) {
   window.codePushReportStatus();
   window.codePushReportStatus = undefined;
}
```

**Comment by lincolnthree** [comment]
@leo6104 What do you think?

**Comment by lincolnthree** [comment]
As a workaround. CodePush needs to be loaded immediately on App start. (I've done this in the Angular root app TypeScript file.)

```
import { codePush } from 'capacitor-codepush';
(() => codePush)(); // to prevent it from being minified away
```

**Comment by o-alexandrov** [comment]
@lincolnthree sorry for pinging about a different issue, but it seems your input might be valuable in #21 
- as it sounds you don't experience [this issue](https://github.com/mapiacompany/capacitor-codepush/issues/21#issuecomment-810062977) on iOS.

Please let us know whether you experience such issue on iOS. It would let us know there whether issue is related to our own setups, or it's not working for everyone.

**Comment by lincolnthree** [comment]
@o-alexandrov It does actually happen on iOS. I've amended my issue report.

**Comment by lincolnthree** [comment]
@o-alexandrov BTW. It's probably better to actually ping me in the issue you'd like me to look at, rather than convolute the discussion of another topic. The topic you're interested in is unrelated and irrelevant info here.
